import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { type RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full">
      <Image
        src={user.profileImageUrl}
        alt="Profile image of user"
        className="mr-4 h-14 w-14 rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex border-b border-indigo-800 p-4">
      <Image
        src={author?.profileImageUrl}
        alt="Profile image of author"
        className="mr-4 h-12 w-12 rounded-full"
        width={48}
        height={48}
      />
      <div>
        <div className="text-indigo-300">
          <span>@{author.username}</span>
          <span> · </span>
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <div className="flex">{post.content}</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-indigo-600  md:max-w-2xl">
          <div className="flex p-4">
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && (
              <div className="flex w-full flex-col">
                <CreatePostWizard />
                <SignOutButton />
              </div>
            )}
          </div>
          <div>
            {isLoading && <div>Loading...</div>}
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
