import { useState } from "react";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { type RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  const [input, setInput] = useState<string>("");
  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
  });

  if (!user) return null;

  return (
    <div className="flex w-full">
      <Image
        src={user.profileImageUrl}
        alt="Profile image of user"
        className="mr-4 h-14 w-14 rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        disabled={isPosting}
      />
      <button onClick={() => mutate({ content: input })}>Post</button>
    </div>
  );
};

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/loading";
import { contextProps } from "@trpc/react-query/shared";
dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex border-b border-indigo-800 p-4">
      <Image
        src={author?.profileImageUrl}
        alt="Profile image of author"
        className="mr-4 h-12 w-12 rounded-full"
        width={48}
        height={48}
      />
      <div>
        <div>
          <span className="font-medium text-indigo-300">
            @{author.username}
          </span>
          <span> · </span>
          <span className="text-indigo-400">
            {dayjs(post.createdAt).fromNow()}
          </span>
        </div>
        <div className="flex text-xl">{post.content}</div>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;

  return (
    <div>
      {data?.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching ASAP
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-indigo-600  md:max-w-2xl">
          <div className="flex p-4">
            {!isSignedIn && <SignInButton />}
            {isSignedIn && (
              <div className="flex w-full flex-col">
                <CreatePostWizard />
              </div>
            )}
          </div>
          <Feed />
          <div className="absolute bottom-3 p-4">
            {isSignedIn && <SignOutButton />}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
